version: "3.3"
services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env   
  app_back:
    restart: on-failure
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app/
    command: npm run dev && npm install
    depends_on:
      - db
    
