version: "3.3"
services:
  db_postgres:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env   


  db_mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - .env 

  app_backend:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend/:/app/
    command: npm instal && npm start
    depends_on:
      - db_postgres
      - db_mongo 

  app_frontend:
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app/
    command: npm install && node app.js
    depends_on:
      - db_postgres
      - db_mongo
      - app_backend
